/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description 健康检查：确认 API 服务存活（文档 §6.2 公开接口）。
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Home
         * @description 首页聚合：精选案例×3 + 上架套餐 + 新闻预览×3 + 关于摘要（占位）。
         */
        get: operations["home_api_v1_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_api_v1_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Case Detail */
        get: operations["case_detail_api_v1_cases__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{slug}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bump Case View
         * @description 浏览量上报：IP+slug 60s 窗口去重（文档 §6.3.4 限流：同 IP 同 slug 60s 计 1 次）。
         */
        post: operations["bump_case_view_api_v1_cases__slug__view_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Packages */
        get: operations["list_packages_api_v1_packages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/packages/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Package Detail */
        get: operations["package_detail_api_v1_packages__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List News */
        get: operations["list_news_api_v1_news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** News Detail */
        get: operations["news_detail_api_v1_news__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Team */
        get: operations["list_team_api_v1_team_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/careers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Careers */
        get: operations["list_careers_api_v1_careers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Site Config
         * @description 站点配置公开输出（占位：第 7 步接入 site_config 单例 + history_items）。
         */
        get: operations["site_config_api_v1_site_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/about/contact-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * About Contact Info
         * @description 联系页信息：地址/电话/邮箱/地图坐标（独立端点便于缓存，§6.3.13）。
         */
        get: operations["about_contact_info_api_v1_about_contact_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description 当前登录用户信息（第 7 步补全 staff 详情）。
         */
        get: operations["get_me_api_v1_admin_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Cases */
        get: operations["admin_list_cases_api_v1_admin_cases_get"];
        put?: never;
        /** Admin Create Case */
        post: operations["admin_create_case_api_v1_admin_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/cases/{pk}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Get Case */
        get: operations["admin_get_case_api_v1_admin_cases__pk__get"];
        /** Admin Update Case */
        put: operations["admin_update_case_api_v1_admin_cases__pk__put"];
        post?: never;
        /** Admin Delete Case */
        delete: operations["admin_delete_case_api_v1_admin_cases__pk__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/cases/{pk}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Admin Case Status */
        patch: operations["admin_case_status_api_v1_admin_cases__pk__status_patch"];
        trace?: never;
    };
    "/api/v1/admin/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Packages */
        get: operations["admin_list_packages_api_v1_admin_packages_get"];
        put?: never;
        /** Admin Create Package */
        post: operations["admin_create_package_api_v1_admin_packages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/packages/{pk}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Get Package */
        get: operations["admin_get_package_api_v1_admin_packages__pk__get"];
        /** Admin Update Package */
        put: operations["admin_update_package_api_v1_admin_packages__pk__put"];
        post?: never;
        /** Admin Delete Package */
        delete: operations["admin_delete_package_api_v1_admin_packages__pk__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/packages/{pk}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Admin Package Status */
        patch: operations["admin_package_status_api_v1_admin_packages__pk__status_patch"];
        trace?: never;
    };
    "/api/v1/admin/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List News */
        get: operations["admin_list_news_api_v1_admin_news_get"];
        put?: never;
        /** Admin Create News */
        post: operations["admin_create_news_api_v1_admin_news_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/news/{pk}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Get News */
        get: operations["admin_get_news_api_v1_admin_news__pk__get"];
        /** Admin Update News */
        put: operations["admin_update_news_api_v1_admin_news__pk__put"];
        post?: never;
        /** Admin Delete News */
        delete: operations["admin_delete_news_api_v1_admin_news__pk__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/news/{pk}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Admin News Status */
        patch: operations["admin_news_status_api_v1_admin_news__pk__status_patch"];
        trace?: never;
    };
    "/api/v1/admin/careers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Careers */
        get: operations["admin_list_careers_api_v1_admin_careers_get"];
        put?: never;
        /** Admin Create Career */
        post: operations["admin_create_career_api_v1_admin_careers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/careers/{pk}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Get Career */
        get: operations["admin_get_career_api_v1_admin_careers__pk__get"];
        /** Admin Update Career */
        put: operations["admin_update_career_api_v1_admin_careers__pk__put"];
        post?: never;
        /** Admin Delete Career */
        delete: operations["admin_delete_career_api_v1_admin_careers__pk__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/careers/{pk}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Admin Career Status */
        patch: operations["admin_career_status_api_v1_admin_careers__pk__status_patch"];
        trace?: never;
    };
    "/api/v1/admin/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Team */
        get: operations["admin_list_team_api_v1_admin_team_get"];
        put?: never;
        /** Admin Create Team */
        post: operations["admin_create_team_api_v1_admin_team_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/team/{pk}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Get Team */
        get: operations["admin_get_team_api_v1_admin_team__pk__get"];
        /** Admin Update Team */
        put: operations["admin_update_team_api_v1_admin_team__pk__put"];
        post?: never;
        /** Admin Delete Team */
        delete: operations["admin_delete_team_api_v1_admin_team__pk__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/team/{pk}/visibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Admin Team Visibility */
        patch: operations["admin_team_visibility_api_v1_admin_team__pk__visibility_patch"];
        trace?: never;
    };
    "/api/v1/admin/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Upload
         * @description 文件上传：MIME 白名单 + ≤10MB + 扩展名白名单 + 路径穿越防护（ADR-007）。
         *
         *     - 落盘 uploads/{folder}/{uuid}.{ext}（文件名不信任原始名）
         *     - 写 uploads 表（owner_type=file, owner_id=NULL, uploaded_by=当前用户）
         *     - 返回 {url, storage_key, mime, size} 供前端表单引用
         */
        post: operations["admin_upload_api_v1_admin_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiListResponse[CareerOut] */
        ApiListResponse_CareerOut_: {
            /** Items */
            items: components["schemas"]["CareerOut"][];
            /** Total */
            total: number;
            /** Page */
            page?: number | null;
            /** Pagesize */
            pageSize?: number | null;
        };
        /** ApiListResponse[CaseListItem] */
        ApiListResponse_CaseListItem_: {
            /** Items */
            items: components["schemas"]["CaseListItem"][];
            /** Total */
            total: number;
            /** Page */
            page?: number | null;
            /** Pagesize */
            pageSize?: number | null;
        };
        /** ApiListResponse[CaseOut] */
        ApiListResponse_CaseOut_: {
            /** Items */
            items: components["schemas"]["CaseOut"][];
            /** Total */
            total: number;
            /** Page */
            page?: number | null;
            /** Pagesize */
            pageSize?: number | null;
        };
        /** ApiListResponse[NewsOut] */
        ApiListResponse_NewsOut_: {
            /** Items */
            items: components["schemas"]["NewsOut"][];
            /** Total */
            total: number;
            /** Page */
            page?: number | null;
            /** Pagesize */
            pageSize?: number | null;
        };
        /** ApiListResponse[PackageListItem] */
        ApiListResponse_PackageListItem_: {
            /** Items */
            items: components["schemas"]["PackageListItem"][];
            /** Total */
            total: number;
            /** Page */
            page?: number | null;
            /** Pagesize */
            pageSize?: number | null;
        };
        /** ApiListResponse[PackageOut] */
        ApiListResponse_PackageOut_: {
            /** Items */
            items: components["schemas"]["PackageOut"][];
            /** Total */
            total: number;
            /** Page */
            page?: number | null;
            /** Pagesize */
            pageSize?: number | null;
        };
        /** ApiResponse[ApiListResponse[CareerOut]] */
        ApiResponse_ApiListResponse_CareerOut__: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["ApiListResponse_CareerOut_"] | null;
        };
        /** ApiResponse[ApiListResponse[CaseListItem]] */
        ApiResponse_ApiListResponse_CaseListItem__: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["ApiListResponse_CaseListItem_"] | null;
        };
        /** ApiResponse[ApiListResponse[CaseOut]] */
        ApiResponse_ApiListResponse_CaseOut__: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["ApiListResponse_CaseOut_"] | null;
        };
        /** ApiResponse[ApiListResponse[NewsOut]] */
        ApiResponse_ApiListResponse_NewsOut__: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["ApiListResponse_NewsOut_"] | null;
        };
        /** ApiResponse[ApiListResponse[PackageListItem]] */
        ApiResponse_ApiListResponse_PackageListItem__: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["ApiListResponse_PackageListItem_"] | null;
        };
        /** ApiResponse[ApiListResponse[PackageOut]] */
        ApiResponse_ApiListResponse_PackageOut__: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["ApiListResponse_PackageOut_"] | null;
        };
        /** ApiResponse[CareerOut] */
        ApiResponse_CareerOut_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["CareerOut"] | null;
        };
        /** ApiResponse[CaseDetailOut] */
        ApiResponse_CaseDetailOut_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["CaseDetailOut"] | null;
        };
        /** ApiResponse[CaseOut] */
        ApiResponse_CaseOut_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["CaseOut"] | null;
        };
        /** ApiResponse[HomeOut] */
        ApiResponse_HomeOut_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["HomeOut"] | null;
        };
        /** ApiResponse[NewsOut] */
        ApiResponse_NewsOut_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["NewsOut"] | null;
        };
        /** ApiResponse[PackageDetailOut] */
        ApiResponse_PackageDetailOut_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["PackageDetailOut"] | null;
        };
        /** ApiResponse[PackageOut] */
        ApiResponse_PackageOut_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["PackageOut"] | null;
        };
        /** ApiResponse[SiteConfigPublicOut] */
        ApiResponse_SiteConfigPublicOut_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["SiteConfigPublicOut"] | null;
        };
        /** ApiResponse[TeamMemberOut] */
        ApiResponse_TeamMemberOut_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["TeamMemberOut"] | null;
        };
        /** ApiResponse[dict] */
        ApiResponse_dict_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
        };
        /** ApiResponse[list[CareerOut]] */
        ApiResponse_list_CareerOut__: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            /** Data */
            data?: components["schemas"]["CareerOut"][] | null;
        };
        /** ApiResponse[list[TeamMemberOut]] */
        ApiResponse_list_TeamMemberOut__: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            /** Data */
            data?: components["schemas"]["TeamMemberOut"][] | null;
        };
        /** Body_admin_upload_api_v1_admin_upload_post */
        Body_admin_upload_api_v1_admin_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /**
         * CareerCreate
         * @description 创建招聘岗位（后台 POST /admin/careers，仅 admin）。
         */
        CareerCreate: {
            /** Title */
            title: string;
            /** Category */
            category: string;
            /** Location */
            location?: string | null;
            /** Type */
            type?: string | null;
            /** Duties */
            duties?: string | null;
            /**
             * Status
             * @default draft
             */
            status: string;
        };
        /**
         * CareerOut
         * @description 招聘岗位输出。
         */
        CareerOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Category */
            category: string;
            /** Location */
            location?: string | null;
            /** Type */
            type?: string | null;
            /** Duties */
            duties?: string | null;
            /** Status */
            status: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * CareerUpdate
         * @description 全量更新招聘岗位（后台 PUT /admin/careers/{id}，仅 admin）。
         */
        CareerUpdate: {
            /** Title */
            title: string;
            /** Category */
            category: string;
            /** Location */
            location?: string | null;
            /** Type */
            type?: string | null;
            /** Duties */
            duties?: string | null;
            /**
             * Status
             * @default draft
             */
            status: string;
        };
        /**
         * CaseCreate
         * @description 创建案例（后台 POST /admin/cases）。
         */
        CaseCreate: {
            /** Slug */
            slug: string;
            /** Category */
            category: string;
            /** Title */
            title: string;
            /**
             * Cover
             * @default
             */
            cover: string;
            /** Gallery */
            gallery?: string[];
            /** Video Url */
            video_url?: string | null;
            /** Summary */
            summary?: string | null;
            /** Content */
            content?: string | null;
            /** Style Tags */
            style_tags?: string[];
            /** House Type Tags */
            house_type_tags?: string[];
            /** Area Range */
            area_range?: string | null;
            /** Location */
            location?: string | null;
            /** Area */
            area?: number | string | null;
            /** Year */
            year?: number | null;
            /** Designer */
            designer?: string | null;
            /** Studio */
            studio?: string | null;
            /** Material Notes */
            material_notes?: string | null;
            /**
             * Price Per Sqm
             * @default 0
             */
            price_per_sqm: number | string;
            /**
             * Is Featured
             * @default false
             */
            is_featured: boolean;
            /**
             * Status
             * @default draft
             */
            status: string;
        };
        /**
         * CaseDetailOut
         * @description 详情：含 prev/next 上下篇（同 category published）。
         */
        CaseDetailOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Category */
            category: string;
            /** Title */
            title: string;
            /** Cover */
            cover: string;
            /** Gallery */
            gallery?: string[];
            /** Video Url */
            video_url?: string | null;
            /** Summary */
            summary?: string | null;
            /** Content */
            content?: string | null;
            /** Style Tags */
            style_tags?: string[];
            /** House Type Tags */
            house_type_tags?: string[];
            /** Area Range */
            area_range?: string | null;
            /** Location */
            location?: string | null;
            /** Area */
            area?: string | null;
            /** Year */
            year?: number | null;
            /** Designer */
            designer?: string | null;
            /** Studio */
            studio?: string | null;
            /** Material Notes */
            material_notes?: string | null;
            /**
             * Price Per Sqm
             * @default 0
             */
            price_per_sqm: string;
            /** Price Note */
            price_note?: string | null;
            /**
             * Is Featured
             * @default false
             */
            is_featured: boolean;
            /**
             * View Count
             * @default 0
             */
            view_count: number;
            /** Status */
            status: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            prev?: components["schemas"]["CaseListItem"] | null;
            next?: components["schemas"]["CaseListItem"] | null;
        };
        /**
         * CaseListItem
         * @description 列表项：不含长文 content（轻量）。
         */
        CaseListItem: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Category */
            category: string;
            /** Title */
            title: string;
            /** Cover */
            cover: string;
            /** Gallery */
            gallery?: string[];
            /** Video Url */
            video_url?: string | null;
            /** Summary */
            summary?: string | null;
            /** Content */
            content?: string | null;
            /** Style Tags */
            style_tags?: string[];
            /** House Type Tags */
            house_type_tags?: string[];
            /** Area Range */
            area_range?: string | null;
            /** Location */
            location?: string | null;
            /** Area */
            area?: string | null;
            /** Year */
            year?: number | null;
            /** Designer */
            designer?: string | null;
            /** Studio */
            studio?: string | null;
            /** Material Notes */
            material_notes?: string | null;
            /**
             * Price Per Sqm
             * @default 0
             */
            price_per_sqm: string;
            /** Price Note */
            price_note?: string | null;
            /**
             * Is Featured
             * @default false
             */
            is_featured: boolean;
            /**
             * View Count
             * @default 0
             */
            view_count: number;
            /** Status */
            status: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * CaseOut
         * @description 案例公开输出（列表项+详情共用基础字段）。
         */
        CaseOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Category */
            category: string;
            /** Title */
            title: string;
            /** Cover */
            cover: string;
            /** Gallery */
            gallery?: string[];
            /** Video Url */
            video_url?: string | null;
            /** Summary */
            summary?: string | null;
            /** Content */
            content?: string | null;
            /** Style Tags */
            style_tags?: string[];
            /** House Type Tags */
            house_type_tags?: string[];
            /** Area Range */
            area_range?: string | null;
            /** Location */
            location?: string | null;
            /** Area */
            area?: string | null;
            /** Year */
            year?: number | null;
            /** Designer */
            designer?: string | null;
            /** Studio */
            studio?: string | null;
            /** Material Notes */
            material_notes?: string | null;
            /**
             * Price Per Sqm
             * @default 0
             */
            price_per_sqm: string;
            /** Price Note */
            price_note?: string | null;
            /**
             * Is Featured
             * @default false
             */
            is_featured: boolean;
            /**
             * View Count
             * @default 0
             */
            view_count: number;
            /** Status */
            status: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * CaseUpdate
         * @description 全量更新案例（后台 PUT /admin/cases/{id}）。
         */
        CaseUpdate: {
            /** Slug */
            slug: string;
            /** Category */
            category: string;
            /** Title */
            title: string;
            /**
             * Cover
             * @default
             */
            cover: string;
            /** Gallery */
            gallery?: string[];
            /** Video Url */
            video_url?: string | null;
            /** Summary */
            summary?: string | null;
            /** Content */
            content?: string | null;
            /** Style Tags */
            style_tags?: string[];
            /** House Type Tags */
            house_type_tags?: string[];
            /** Area Range */
            area_range?: string | null;
            /** Location */
            location?: string | null;
            /** Area */
            area?: number | string | null;
            /** Year */
            year?: number | null;
            /** Designer */
            designer?: string | null;
            /** Studio */
            studio?: string | null;
            /** Material Notes */
            material_notes?: string | null;
            /**
             * Price Per Sqm
             * @default 0
             */
            price_per_sqm: number | string;
            /**
             * Is Featured
             * @default false
             */
            is_featured: boolean;
            /**
             * Status
             * @default draft
             */
            status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HomeOut
         * @description 首页聚合（§6.3.1）：精选案例×3 + 上架套餐 + 新闻预览×3 + 关于摘要。
         */
        HomeOut: {
            /** Featured Cases */
            featured_cases?: components["schemas"]["CaseListItem"][];
            /** Published Packages */
            published_packages?: components["schemas"]["PackageListItem"][];
            /** News Preview */
            news_preview?: components["schemas"]["NewsOut"][];
            /**
             * About Summary
             * @default
             */
            about_summary: string;
        };
        /**
         * NewsCreate
         * @description 创建资讯（后台 POST /admin/news）。
         */
        NewsCreate: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Category */
            category: string;
            /**
             * Cover
             * @default
             */
            cover: string;
            /** Summary */
            summary?: string | null;
            /** Content */
            content?: string | null;
            /**
             * Status
             * @default draft
             */
            status: string;
        };
        /**
         * NewsOut
         * @description 资讯输出（列表项+详情）。
         */
        NewsOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Category */
            category: string;
            /** Cover */
            cover: string;
            /** Summary */
            summary?: string | null;
            /** Content */
            content?: string | null;
            /** Published At */
            published_at?: string | null;
            /** Status */
            status: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * NewsUpdate
         * @description 全量更新资讯（后台 PUT /admin/news/{id}）。
         */
        NewsUpdate: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Category */
            category: string;
            /**
             * Cover
             * @default
             */
            cover: string;
            /** Summary */
            summary?: string | null;
            /** Content */
            content?: string | null;
            /**
             * Status
             * @default draft
             */
            status: string;
        };
        /**
         * PackageCreate
         * @description 创建套餐（后台 POST /admin/packages）。
         */
        PackageCreate: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Cover
             * @default
             */
            cover: string;
            /** Summary */
            summary?: string | null;
            /** Description */
            description?: string | null;
            /** Applicable House Type */
            applicable_house_type?: string | null;
            /**
             * Price Per Sqm
             * @default 0
             */
            price_per_sqm: number | string;
            /**
             * Price From
             * @default 0
             */
            price_from: number | string;
            /**
             * Area Step Coefficient
             * @default 1
             */
            area_step_coefficient: number | string;
            /**
             * Status
             * @default draft
             */
            status: string;
            /** Process Steps */
            process_steps?: components["schemas"]["PackageProcessStepCreate"][];
        };
        /**
         * PackageDetailOut
         * @description 详情：含 description 长文 + 流程步骤。
         */
        PackageDetailOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Cover */
            cover: string;
            /** Summary */
            summary?: string | null;
            /** Applicable House Type */
            applicable_house_type?: string | null;
            /**
             * Price Per Sqm
             * @default 0
             */
            price_per_sqm: string;
            /**
             * Price From
             * @default 0
             */
            price_from: string;
            /**
             * Area Step Coefficient
             * @default 1
             */
            area_step_coefficient: string;
            /** Price Note */
            price_note?: string | null;
            /** Status */
            status: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Description */
            description?: string | null;
            /** Process Steps */
            process_steps?: components["schemas"]["PackageProcessStepOut"][];
        };
        /**
         * PackageListItem
         * @description 列表项（与 PackageOut 相同结构，语义区分）。
         */
        PackageListItem: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Cover */
            cover: string;
            /** Summary */
            summary?: string | null;
            /** Applicable House Type */
            applicable_house_type?: string | null;
            /**
             * Price Per Sqm
             * @default 0
             */
            price_per_sqm: string;
            /**
             * Price From
             * @default 0
             */
            price_from: string;
            /**
             * Area Step Coefficient
             * @default 1
             */
            area_step_coefficient: string;
            /** Price Note */
            price_note?: string | null;
            /** Status */
            status: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * PackageOut
         * @description 套餐公开输出（列表项）。不含 description 长文与步骤。
         */
        PackageOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Cover */
            cover: string;
            /** Summary */
            summary?: string | null;
            /** Applicable House Type */
            applicable_house_type?: string | null;
            /**
             * Price Per Sqm
             * @default 0
             */
            price_per_sqm: string;
            /**
             * Price From
             * @default 0
             */
            price_from: string;
            /**
             * Area Step Coefficient
             * @default 1
             */
            area_step_coefficient: string;
            /** Price Note */
            price_note?: string | null;
            /** Status */
            status: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * PackageProcessStepCreate
         * @description 套餐流程步骤（嵌套在 PackageCreate 内）。
         */
        PackageProcessStepCreate: {
            /** Step No */
            step_no: number;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
        };
        /**
         * PackageProcessStepOut
         * @description 套餐步骤输出。
         */
        PackageProcessStepOut: {
            /** Id */
            id: number;
            /** Step No */
            step_no: number;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
        };
        /**
         * PackageUpdate
         * @description 全量更新套餐（后台 PUT /admin/packages/{id}）。
         */
        PackageUpdate: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Cover
             * @default
             */
            cover: string;
            /** Summary */
            summary?: string | null;
            /** Description */
            description?: string | null;
            /** Applicable House Type */
            applicable_house_type?: string | null;
            /**
             * Price Per Sqm
             * @default 0
             */
            price_per_sqm: number | string;
            /**
             * Price From
             * @default 0
             */
            price_from: number | string;
            /**
             * Area Step Coefficient
             * @default 1
             */
            area_step_coefficient: number | string;
            /**
             * Status
             * @default draft
             */
            status: string;
            /** Process Steps */
            process_steps?: components["schemas"]["PackageProcessStepCreate"][];
        };
        /**
         * SiteConfigPublicOut
         * @description 站点配置公开输出（§6.3.11）：品牌/公司/流程/联系/社媒/历程。
         */
        SiteConfigPublicOut: {
            /**
             * Id
             * @default 1
             */
            id: number;
            /** Company Intro */
            company_intro?: string | null;
            /** Brand Intro */
            brand_intro?: string | null;
            /** Process Intro */
            process_intro?: string | null;
            /** Contact Info */
            contact_info?: {
                [key: string]: unknown;
            };
            /** Social Links */
            social_links?: {
                [key: string]: unknown;
            }[];
            /** History Items */
            history_items?: unknown[];
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * TeamMemberCreate
         * @description 创建团队成员（后台 POST /admin/team）。
         */
        TeamMemberCreate: {
            /** Name */
            name: string;
            /** Title */
            title?: string | null;
            /** Avatar */
            avatar?: string | null;
            /** Specialty */
            specialty?: string | null;
            /** Bio */
            bio?: string | null;
            /** Staff Id */
            staff_id?: number | null;
            /**
             * Order
             * @default 0
             */
            order: number;
            /**
             * Active
             * @default true
             */
            active: boolean;
        };
        /**
         * TeamMemberOut
         * @description 团队成员输出。
         */
        TeamMemberOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Title */
            title?: string | null;
            /** Avatar */
            avatar?: string | null;
            /** Specialty */
            specialty?: string | null;
            /** Bio */
            bio?: string | null;
            /** Staff Id */
            staff_id?: number | null;
            /**
             * Order
             * @default 0
             */
            order: number;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Created At */
            created_at?: string | null;
        };
        /**
         * TeamMemberUpdate
         * @description 全量更新团队成员（后台 PUT /admin/team/{id}）。
         */
        TeamMemberUpdate: {
            /** Name */
            name: string;
            /** Title */
            title?: string | null;
            /** Avatar */
            avatar?: string | null;
            /** Specialty */
            specialty?: string | null;
            /** Bio */
            bio?: string | null;
            /** Staff Id */
            staff_id?: number | null;
            /**
             * Order
             * @default 0
             */
            order: number;
            /**
             * Active
             * @default true
             */
            active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_dict_"];
                };
            };
        };
    };
    home_api_v1_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_HomeOut_"];
                };
            };
        };
    };
    list_cases_api_v1_cases_get: {
        parameters: {
            query?: {
                cat?: string | null;
                /** @description 风格标签，逗号分隔多值 */
                style?: string | null;
                /** @description 户型标签，逗号分隔多值 */
                house_type?: string | null;
                area_range?: string | null;
                sort?: string;
                keyword?: string | null;
                page?: number | null;
                pageSize?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ApiListResponse_CaseListItem__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    case_detail_api_v1_cases__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CaseDetailOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bump_case_view_api_v1_cases__slug__view_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_packages_api_v1_packages_get: {
        parameters: {
            query?: {
                type?: string | null;
                page?: number | null;
                pageSize?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ApiListResponse_PackageListItem__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    package_detail_api_v1_packages__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PackageDetailOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_news_api_v1_news_get: {
        parameters: {
            query?: {
                cat?: string | null;
                page?: number | null;
                pageSize?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ApiListResponse_NewsOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    news_detail_api_v1_news__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NewsOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_team_api_v1_team_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_TeamMemberOut__"];
                };
            };
        };
    };
    list_careers_api_v1_careers_get: {
        parameters: {
            query?: {
                cat?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_CareerOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    site_config_api_v1_site_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_SiteConfigPublicOut_"];
                };
            };
        };
    };
    about_contact_info_api_v1_about_contact_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_dict_"];
                };
            };
        };
    };
    get_me_api_v1_admin_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    admin_list_cases_api_v1_admin_cases_get: {
        parameters: {
            query?: {
                cat?: string | null;
                status?: string | null;
                keyword?: string | null;
                page?: number | null;
                pageSize?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ApiListResponse_CaseOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_create_case_api_v1_admin_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CaseOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_case_api_v1_admin_cases__pk__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CaseOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_case_api_v1_admin_cases__pk__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CaseOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_delete_case_api_v1_admin_cases__pk__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_case_status_api_v1_admin_cases__pk__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CaseOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_packages_api_v1_admin_packages_get: {
        parameters: {
            query?: {
                type?: string | null;
                status?: string | null;
                page?: number | null;
                pageSize?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ApiListResponse_PackageOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_create_package_api_v1_admin_packages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PackageDetailOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_package_api_v1_admin_packages__pk__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PackageDetailOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_package_api_v1_admin_packages__pk__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackageUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PackageDetailOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_delete_package_api_v1_admin_packages__pk__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_package_status_api_v1_admin_packages__pk__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PackageOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_news_api_v1_admin_news_get: {
        parameters: {
            query?: {
                cat?: string | null;
                status?: string | null;
                page?: number | null;
                pageSize?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ApiListResponse_NewsOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_create_news_api_v1_admin_news_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NewsOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_news_api_v1_admin_news__pk__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NewsOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_news_api_v1_admin_news__pk__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NewsOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_delete_news_api_v1_admin_news__pk__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_news_status_api_v1_admin_news__pk__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NewsOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_careers_api_v1_admin_careers_get: {
        parameters: {
            query?: {
                cat?: string | null;
                status?: string | null;
                page?: number | null;
                pageSize?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ApiListResponse_CareerOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_create_career_api_v1_admin_careers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CareerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CareerOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_career_api_v1_admin_careers__pk__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CareerOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_career_api_v1_admin_careers__pk__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CareerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CareerOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_delete_career_api_v1_admin_careers__pk__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_career_status_api_v1_admin_careers__pk__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CareerOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_team_api_v1_admin_team_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_TeamMemberOut__"];
                };
            };
        };
    };
    admin_create_team_api_v1_admin_team_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamMemberCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_TeamMemberOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_team_api_v1_admin_team__pk__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_TeamMemberOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_team_api_v1_admin_team__pk__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamMemberUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_TeamMemberOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_delete_team_api_v1_admin_team__pk__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_team_visibility_api_v1_admin_team__pk__visibility_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_TeamMemberOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_upload_api_v1_admin_upload_post: {
        parameters: {
            query?: {
                folder?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_admin_upload_api_v1_admin_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
